services:
  luckperms:
    container_name: luckperms
    hostname: luckperms
    image: mariadb
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - luckperms-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --wait-timeout=28800'
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LUCKPERMS_DB}
      MYSQL_USER: ${LUCKPERMS_DB_USER} 
      MYSQL_PASSWORD: ${LUCKPERMS_DB_PASSWORD}
    networks:
      - mc-network

  adminer:
    image: adminer
    ports:
      - "8806:8080"

volumes:
  luckperms-data: {}
