services:
  rcon:
    container_name: rcon
    hostname: rcon
    image: itzg/rcon
    restart: unless-stopped
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      REPLACE_ENV_DURING_SYNC: "TRUE"
      RWA_RCON_PASSWORD: ${MC_RCON_PASSWORD}
      RWA_ADMIN: "TRUE"
      RWA_USERNAME: admin
      RWA_PASSWORD: ${MC_RCON_USER_ADMIN_PASSWORD}
      RWA_RCON_HOST: mc-survival
    volumes:
      - rcon-data:/opt/rcon-web-admin/db
    networks:
      - mc-rcon
  luckperms:
    container_name: luckperms
    hostname: luckperms
    image: mariadb
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - luckperms-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --wait-timeout=28800'
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LUCKPERMS_DB}
      MYSQL_USER: ${LUCKPERMS_DB_USER} 
      MYSQL_PASSWORD: ${LUCKPERMS_DB_PASSWORD}
    networks:
      - mc-network
  mc-proxy:
    container_name: mc-proxy
    hostname: mc-proxy
    image: itzg/mc-proxy
    restart: unless-stopped
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    volumes:
      - mc-proxy-data:/server
      - ./config/proxy:/config
    environment:
      TYPE: VELOCITY
      MINECRAFT_VERSION: 1.20.1
      REPLACE_ENV_DURING_SYNC: "TRUE"
      CFG_VELOCITY_SECRET: ${VELOCITY_SECRET}
      CFG_LUCKPERMS_DB: ${LUCKPERMS_DB}
      CFG_LUCKPERMS_DB_USER: ${LUCKPERMS_DB_USER}
      CFG_LUCKPERMS_DB_PASSWORD: ${LUCKPERMS_DB_PASSWORD}
      MODRINTH_PROJECTS: |
        simple-voice-chat:gN7gtGyZ
        luckperms:ACa3exrC
    networks:
      - mc-network
    depends_on:
      - luckperms
      - mc-survival
      - mc-creative
  mc-survival:
    container_name: mc-survival
    hostname: mc-survival
    extends:
      file: mc-common.yml
      service: mc
    environment:
      MODE: survival
      DIFFICULTY: hard
      SEED: 188557497422300983
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /modpack/aloha-snack-bar-s3.mrpack
      MAX_MEMORY: 16G
      CFG_SERVER_NAME: survival
    volumes:
      - mc-survival-data:/data
      - ./modpack:/modpack:ro
      - ./config/minecraft:/config
    depends_on:
      - luckperms
    networks:
      - mc-network
      - mc-rcon
  mc-creative:
    container_name: mc-creative
    hostname: mc-creative
    extends:
      file: mc-common.yml
      service: mc
    environment:
      MODE: creative
      LEVEL_TYPE: FLAT
      GENERATE_STRUCTURES: false
      MAX_MEMORY: 4G
      CFG_SERVER_NAME: creative
      MODRINTH_PROJECTS: |
        axiom:61myQqfU
        abstract:8T0l0QkL
        botania:t7kGxx07
        built:ONN2RViA
        clutter:t7kGxx07
        convenient-decor:JrcEJiEH
        ferrite-core:unerR5MN
        krypton:jiDwS0W1
        lithium:vuuAe7ZA
        macaws-stairs:XNlrOt9m
        memoryleakfix:5xvCCRjJ
        noisium:erSJnRcq
        spark:XGW2fviP
        starlight:XGIsoVGT
    volumes:
      - mc-creative-data:/data
      - ./config/minecraft:/config
    depends_on:
      - luckperms
    networks:
      - mc-network
      - mc-rcon
volumes:
  rcon-data: {}
  luckperms-data: {}
  mc-survival-data: {}
  mc-creative-data: {}
  mc-proxy-data: {}
networks:
  mc-network:
    driver: bridge
  mc-rcon:
    driver: bridge
