services:
  mc:
    tty: true
    stdin_open: true
    restart: unless-stopped
    image: itzg/minecraft-server:java21-graalvm
    expose:
      - "25565:25565/tcp"
      - "25565:24454/udp"
    environment:
      EULA: true
      VERSION: 1.20.1
      TYPE: FABRIC
      INIT_MEMORY: 1G
      USE_MEOWICE_FLAGS: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      COPY_CONFIG_DEST: /data
      JVM_XX_OPTS: |
        -XX:+UnlockExperimentalVMOptions
        -XX:G1NewSizePercent=40
        -XX:G1MaxNewSizePercent=50
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=15
        -XX:InitiatingHeapOccupancyPercent=20
      CFG_VELOCITY_SECRET: ${VELOCITY_SECRET}
      CFG_LUCKPERMS_DB: ${LUCKPERMS_DB}
      CFG_LUCKPERMS_DB_USER: ${LUCKPERMS_DB_USER}
      CFG_LUCKPERMS_DB_PASSWORD: ${LUCKPERMS_DB_PASSWORD}
      CFG_DISCORD_BOT_API_TOKEN: ${DISCORD_BOT_API_TOKEN}
      CFG_DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      CFG_DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
      RCON_PASSWORD: ${MC_RCON_PASSWORD}
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_FORCE_SYNCHRONIZE: true
      MODRINTH_PROJECTS: |
        crossstitch:dJioNlO8
        fabricproxy-lite:XJmDAnj5
        luckperms:7PNj6nCm
        sdlink:U3TpSJoR
        mysql-jdbc:94JxXm7O
        placeholder-api:DaV2ycYi
        solstice-essentials:fmCpQgOo
        vanilla-permissions:Qw3egHgT

        audioplayer:hDi749ai
        carpet:K0Wj117C
        image2map:T71Apams
        chunky:NHWYq9at
        chunkyborder:74w5ono0
        
        recipecooldown:oe5KEgWu
        servercore:m978FuzE
        threadtweak:gBP1GqtK
        tt20:qmNvXoqy
        vmp-fabric:sV8lIBhJ
