services:
  rcon:
    container_name: rcon
    hostname: rcon
    image: itzg/rcon
    restart: unless-stopped
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      REPLACE_ENV_DURING_SYNC: "TRUE"
      RWA_RCON_PASSWORD: ${MC_RCON_PASSWORD}
      RWA_ADMIN: "TRUE"
      RWA_USERNAME: admin
      RWA_PASSWORD: ${MC_RCON_USER_ADMIN_PASSWORD}
      RWA_RCON_HOST: mc-survival
    volumes:
      - rcon-data:/opt/rcon-web-admin/db
    networks:
      - mc-rcon

  backups:
    container_name: backups
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc-survival
      RCON_PASSWORD: ${MC_RCON_PASSWORD}
      INITIAL_DELAY: 0
    volumes:
      - mc-survival-data:/data:ro
      - ./mc-backups:/backups
    networks:
      - mc-rcon
  
volumes:
  rcon-data: {}
