services:
  mc-proxy:
    container_name: mc-proxy
    hostname: mc-proxy
    image: itzg/mc-proxy
    restart: unless-stopped
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    environment:
      TYPE: VELOCITY
      MINECRAFT_VERSION: 1.20.1
      REPLACE_ENV_DURING_SYNC: "TRUE"
      CFG_VELOCITY_SECRET: ${VELOCITY_SECRET}
      CFG_LUCKPERMS_DB: ${LUCKPERMS_DB}
      CFG_LUCKPERMS_DB_USER: ${LUCKPERMS_DB_USER}
      CFG_LUCKPERMS_DB_PASSWORD: ${LUCKPERMS_DB_PASSWORD}
      MODRINTH_PROJECTS: |
        simple-voice-chat:gN7gtGyZ
        luckperms:ACa3exrC
    volumes:
      - mc-proxy-data:/server
      - ./config/proxy:/config
    depends_on:
      - luckperms
      - mc-survival
      - mc-creative
    networks:
      - dbs
      - mc-network

  mc-survival:
    container_name: mc-survival
    hostname: mc-survival
    extends:
      file: mc-common.yml
      service: mc
    environment:
      MODE: survival
      DIFFICULTY: hard
      SEED: 188557497422300983
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /modpack/aloha-snack-bar-s3.mrpack
      MAX_MEMORY: 16G
      CFG_SERVER_NAME: survival
      DATAPACKS: /datapacks
      REMOVE_OLD_DATAPACKS: true
    volumes:
      - mc-survival-data:/data
      - ./config/minecraft:/config
      - ./datapacks:/datapacks:ro
      - ./modpack:/modpack:ro
    depends_on:
      - luckperms
    networks:
      - dbs
      - mc-network
      - mc-rcon

  mc-creative:
    container_name: mc-creative
    hostname: mc-creative
    extends:
      file: mc-common.yml
      service: mc
    environment:
      MODE: creative
      LEVEL_TYPE: FLAT
      GENERATE_STRUCTURES: false
      MAX_MEMORY: 4G
      CFG_SERVER_NAME: creative
      GENERATOR_SETTINGS: >-4
          {
              "layers": [
                  {
                      "block": "minecraft:white_stained_glass",
                      "height": 1
                  }
              ]
          }
      MODRINTH_PROJECTS: |
        carpet:K0Wj117C
        fabricproxy-lite:XJmDAnj5
        luckperms:7PNj6nCm
        crossstitch:dJioNlO8
        c2me-fabric:s4WOiNtz
        vmp-fabric:sV8lIBhJ
        threadtweak:gBP1GqtK
        alternate-current:ckuIQWvo
        recipecooldown:oe5KEgWu
        entity-view-distance:piYJfUyC
        tt20:qmNvXoqy
        lmd:rOkgwJ12
        placeholder-api:DaV2ycYi
        audioplayer:hDi749ai
        vanilla-permissions:Qw3egHgT
        servercore:m978FuzE
        image2map:T71Apams
        mysql-jdbc:94JxXm7O
        sdlink:U3TpSJoR
        styled-chat:pwr7uYCH
        axiom:61myQqfU
        abstract:8T0l0QkL
        botania:t7kGxx07
        built:ONN2RViA
        clutter:t7kGxx07
        convenient-decor:JrcEJiEH
        distanthorizons:vSDePnsB
        ferrite-core:unerR5MN
        krypton:jiDwS0W1
        lithium:vuuAe7ZA
        macaws-stairs:XNlrOt9m
        memoryleakfix:5xvCCRjJ
        noisium:erSJnRcq
        spark:XGW2fviP
        starlight:XGIsoVGT
    volumes:
      - mc-creative-data:/data
      - ./config/minecraft:/config
    depends_on:
      - luckperms
    networks:
      - dbs
      - mc-network
      - mc-rcon

  rcon:
    container_name: rcon
    hostname: rcon
    image: itzg/rcon
    restart: unless-stopped
    ports:
      - "4326:4326"
    environment:
      REPLACE_ENV_DURING_SYNC: "TRUE"
      RWA_RCON_PASSWORD: ${MC_RCON_PASSWORD}
      RWA_ADMIN: "TRUE"
      RWA_USERNAME: admin
      RWA_PASSWORD: ${MC_RCON_USER_ADMIN_PASSWORD}
      RWA_RCON_HOST: mc-survival
    volumes:
      - mc-rcon-data:/opt/rcon-web-admin/db
    networks:
      - mc-rcon

  backups:
    container_name: backups
    image: itzg/mc-backup
    user: "1000"
    environment:
      BACKUP_INTERVAL: 12h
      RCON_HOST: mc-survival
      RCON_PASSWORD: ${MC_RCON_PASSWORD}
    volumes:
      - mc-survival-data:/data:ro
      - ./mc-backups:/backups
    networks:
      - mc-rcon 

  luckperms:
    container_name: luckperms
    hostname: luckperms
    image: mariadb
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - luckperms-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --wait-timeout=28800'
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LUCKPERMS_DB}
      MYSQL_USER: ${LUCKPERMS_DB_USER} 
      MYSQL_PASSWORD: ${LUCKPERMS_DB_PASSWORD}
    networks:
      - dbs

  adminer:
    image: adminer
    ports:
      - "8806:8080"
    networks:
      - dbs

volumes:
  luckperms-data: {}
  mc-creative-data: {}
  mc-proxy-data: {}
  mc-rcon-data: {}
  mc-survival-data: {}

networks:
  dbs:
    driver: bridge
  mc-network:
    driver: bridge
  mc-rcon:
    driver: bridge
