features:
  # Stops the server from loading spawn chunks.
  disable-spawn-chunks: false
  # Prevents lagspikes caused by players moving into unloaded chunks.
  prevent-moving-into-unloaded-chunks: false
  # The amount of ticks between auto-saves when /save-on is active.
  autosave-interval: 6000
  # The fraction that decides the chance of experience orbs being able to merge with each other. (1 = 100%, 40 = 2.5%)
  # Note that just like in vanilla, experience orbs will still need to be of the same size to actually merge.
  xp-merge-fraction: 40
  # The radius in blocks that experience orbs will merge at.
  xp-merge-radius: 0.5
  # The radius in blocks that items will merge at.
  item-merge-radius: 0.5
  lobotomize-villagers:
    # Makes villagers tick less often if they are stuck in a 1x1 space.
    enabled: true
    # Decides the interval in between villager ticks when lobotomized.
    tick-interval: 20

# Automatically modifies dynamic settings based on the server performance.
dynamic:
  enabled: true
  # The average MSPT to target.
  target-mspt: 50
  dynamic-settings:
    - setting: 'CHUNK_TICK_DISTANCE'
      max: 10
      min: 2
      increment: 1
      interval: 15

    - setting: 'MOBCAP_PERCENTAGE'
      max: 100
      min: 30
      increment: 10
      interval: 15

    - setting: 'SIMULATION_DISTANCE'
      max: 10
      min: 2
      increment: 1
      interval: 15

    - setting: 'VIEW_DISTANCE'
      max: 10
      min: 2
      increment: 1
      interval: 150

breeding-cap:
  # Enables breeding caps.
  enabled: true
  villagers:
    limit: 16
    range: 64

  animals:
    limit: 16
    range: 64


# Gives more control over mob spawning.
mob-spawning:
  # Mobcap settings for zombie reinforcements.
  # ► enforce-mobcaps = Whether to enforce mobcaps for this type of mobspawning.
  # ► additional-capacity = Additional capacity for this specific mobcap. Decides how much it can spawn over the regular mobcap.
  # It is recommended to allow them to spawn a bit over the regular mobcap as they would otherwise never get a chance to spawn.
  zombie-reinforcements:
    enforce-mobcap: false
    additional-capacity: 32

  # Mobcap settings for zombified piglin spawning from nether portal random ticks.
  nether-portal-randomticks:
    enforce-mobcap: false
    additional-capacity: 32

  # Mobcap settings for mobs spawned from monster spawners.
  monster-spawners:
    enforce-mobcap: false
    additional-capacity: 32

  # A list of mob categories with their respective mobcap and spawn interval.
  # ► category = The vanilla spawn category.
  # ► mobcap = The maximum amount of entities in the same category that can spawn near a player.
  # ► spawn-interval = The interval between spawn attempts in ticks. Higher values mean less frequent spawn attempts.
  categories:
    - category: 'MONSTER'
      mobcap: 70
      spawn-interval: 1

    - category: 'CREATURE'
      mobcap: 10
      spawn-interval: 400

    - category: 'AMBIENT'
      mobcap: 15
      spawn-interval: 1

    - category: 'AXOLOTLS'
      mobcap: 5
      spawn-interval: 1

    - category: 'UNDERGROUND_WATER_CREATURE'
      mobcap: 5
      spawn-interval: 1

    - category: 'WATER_CREATURE'
      mobcap: 5
      spawn-interval: 1

    - category: 'WATER_AMBIENT'
      mobcap: 20
      spawn-interval: 1

commands:
  status-enabled: true
  mobcaps-enabled: true
  colors:
    # The colors used in command feedback. You can use hex codes or minecraft legacy color names.
    # The primary color is the most used color in command feedback.
    primary: 'dark_aqua'
    # The secondary color is used for highlighting important information, like values.
    secondary: 'green'
    # The tertiary color is mostly used for text in titles.
    tertiary: 'aqua'


# Activation range can drastically reduce the amount of lag caused by ticking entities.
# It does this by cleverly skipping certain entity ticks based on the distance to players and other factors, like immunity checks.
# Immunity checks determine whether an entity should be ticked even when it's outside the activation range, like for example when it is falling or takes damage.
# Note: while this is a very powerful feature, it can still slow down mobfarms and break very specific technical contraptions.
activation-range:
  enabled: true
  tick-new-entities: true
  use-vertical-range: true
  skip-non-immune: true
  villager-tick-panic: true
  villager-work-immunity-after: 20
  villager-work-immunity-for: 20
  excluded-entity-types:
    - 'minecraft:hopper_minecart'
    - 'minecraft:ghast'
    - 'minecraft:warden'
  default-activation-type:
    activation-range: 16
    tick-interval: 20
    wakeup-interval: -1
    extra-height-up: false
    extra-height-down: false

  # A list of custom activation types.
  # ► name = The name of the activation type.
  # ► entity-matcher = A list of conditions to filter entities. Only one of these conditions needs to be met for an entity to match.
  # ► If an entity matches multiple activation types, the one highest in the list will be used. The conditions accept the following formats:
  #   - Entity type matching    |   Uses the entity type's identifier.  |  'minecraft:zombie' matches zombies, but for example not husks or drowned.
  #   - Typeof class matching   |   Uses the 'typeof:' prefix.          |  'typeof:monster' matches all monsters.
  # ► Available typeof classes: mob, monster, raider, neutral, ambient, animal, water_animal, flying_animal, flying_monster, villager, projectile.
  custom-activation-types:
    - name: 'raider'
      activation-range: 48
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'typeof:raider'

    - name: 'water'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 60
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:water_animal'

    - name: 'villager'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 30
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:villager'

    - name: 'zombie'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'minecraft:zombie'
        - 'minecraft:husk'

    - name: 'monster-below'
      activation-range: 32
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: true
      entity-matcher:
        - 'minecraft:creeper'
        - 'minecraft:slime'
        - 'minecraft:magma_cube'
        - 'minecraft:hoglin'

    - name: 'flying-monster'
      activation-range: 48
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'minecraft:ghast'
        - 'minecraft:phantom'

    - name: 'monster'
      activation-range: 32
      tick-interval: 20
      wakeup-interval: 20
      extra-height-up: true
      extra-height-down: false
      entity-matcher:
        - 'typeof:monster'

    - name: 'animal'
      activation-range: 16
      tick-interval: 20
      wakeup-interval: 60
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:animal'
        - 'typeof:ambient'

    - name: 'creature'
      activation-range: 24
      tick-interval: 20
      wakeup-interval: 30
      extra-height-up: false
      extra-height-down: false
      entity-matcher:
        - 'typeof:mob'
